#!/usr/bin/env python3
"""Build the railway track fastener specifications article JSON cleanly."""
import json
from pathlib import Path

LANGS = ['en', 'zh', 'es', 'ar', 'fr', 'pt', 'ru', 'ja', 'de', 'hi']


def t(en, zh, es, ar, fr, pt, ru, ja, de, hi):
    return {
        'en': en, 'zh': zh, 'es': es, 'ar': ar, 'fr': fr,
        'pt': pt, 'ru': ru, 'ja': ja, 'de': de, 'hi': hi
    }


# Section 1: Overview
s1_heading = t(
    "Railway Track Fastener Systems: Global Overview",
    "铁路轨道紧固件系统：全球概览",
    "Sistemas de Sujetadores de Vía Férrea: Visión Global",
    "أنظمة مثبتات مسارات السكك الحديدية: نظرة عامة عالمية",
    "Systèmes d'Attaches Ferroviaires : Aperçu Mondial",
    "Sistemas de Fixadores de Trilhos Ferroviários: Visão Geral Global",
    "Системы крепежа железнодорожных путей: глобальный обзор",
    "鉄道軌道締結装置システム：世界的概要",
    "Eisenbahnschienen-Befestigungssysteme: Globaler Überblick",
    "रेलवे ट्रैक फास्टनर सिस्टम: वैश्विक अवलोकन"
)

s1_en = (
    "Railway track fastener systems are critical safety components that maintain rail alignment, gauge, and structural integrity under extreme dynamic loads. Modern high-speed and heavy-haul networks depend on engineered fastening assemblies rather than traditional rail spikes alone. A complete fastening system typically includes elastic <a href=\"/en/products/track-bolts\" class=\"text-primary-600 hover:text-primary-800 underline\">track bolts</a>, spring <a href=\"/en/products/spring-washers\" class=\"text-primary-600 hover:text-primary-800 underline\">spring washers</a>, insulating bushings, baseplates or tie plates, and either elastic clips or screw spikes that clamp the rail foot to the sleeper.\n\n"
    "Three specification frameworks dominate global railway procurement: <a href=\"/en/industry/mining-fastener-specifications\" class=\"text-primary-600 hover:text-primary-800 underline\">Pandrol</a> e-clip systems (originally British, now part of the Delachaux Group) cover more than 80 countries and are specified on the majority of heavy-haul African, Middle Eastern, and Asian networks. The Pandrol Fastclip and e-clip families hold the largest installed base worldwide. Vossloh fastening systems, manufactured in Germany and supplied through Wirthwein and Schwihag subsidiaries, dominate European high-speed corridors including Deutsche Bahn, SNCF, and RENFE, and increasingly penetrate North Africa, India, and Southeast Asia through licensed production. The American Railway Engineering and Maintenance-of-Way Association (AREMA) portfolio governs North American freight, Canadian National, and parts of Mexico and Central America, with tie plates, cut spikes, and screw spikes being the legacy defaults and elastic clips gaining ground on modern concrete-tie installations.\n\n"
    "Understanding the differences between these three families is essential for procurement officers, project engineers, and fastener traders serving cross-border tenders. A typical metric Pandrol e-clip on a concrete sleeper (such as the e-2055 or e-2060 series) operates at a toe load of 8.8 to 11.0 kN per clip, while a comparable Vossloh W14 or Skl14 clip delivers 9 to 11 kN. AREMA spring-clip equivalents such as the Safelok I or Pandrol PR-clip family operate in a similar 7 to 10 kN window but use different anchorage geometry. Rail joint assemblies using <a href=\"/en/products/fish-plates\" class=\"text-primary-600 hover:text-primary-800 underline\">fish plates</a> (also called joint bars or angle bars) and <a href=\"/en/products/anchor-bolts\" class=\"text-primary-600 hover:text-primary-800 underline\">anchor bolts</a> remain mandatory in continuous-welded-rail (CWR) transition zones, insulated joint locations, and at bridge approaches where rail expansion must be controlled.\n\n"
    "For TradeGo customers sourcing from China, India, and Türkiye for African, Middle Eastern, and Latin American tenders, the practical implications are significant. Most Asian and Middle Eastern rail authorities accept Pandrol or Vossloh equivalents supplied under license, with third-party testing per EN 13146 (Europe), UIC 864 (international), or AREMA Chapter 5 (North America) typically required. Material grades most commonly requested are 60Si2Mn or 51CrV4 spring steel for elastic clips (1,200-1,400 MPa tensile), Grade 8.8 or 10.9 for high-strength <a href=\"/en/products/hex-nuts\" class=\"text-primary-600 hover:text-primary-800 underline\">track bolts and hex nuts</a>, and Q345B or A36 steel for tie plates and baseplates. Hot-dip galvanizing per EN ISO 1461 (coating thickness 55-85 μm) is the default corrosion-protection specification in tropical and coastal networks, with some Brazilian, Saudi, and Australian tenders requiring a duplex epoxy topcoat for additional salt-spray resistance.\n\n"
    "Procurement volumes vary dramatically by application. A standard 25-tonne container loads approximately 800,000 Pandrol e-clips or 400,000 Vossloh Skl clips, while track bolts in M22 × 130 mm or M24 × 150 mm sizes run 25,000 to 30,000 pieces per container. Fish plates in 4-hole or 6-hole configurations pack 8,000 to 12,000 sets per container depending on rail weight (UIC 54, UIC 60, AREMA 115RE, or AREMA 136RE). This article provides the technical specifications, dimensional tolerances, mechanical properties, and quality-control procedures that procurement teams need to specify, source, and inspect railway track fastening components to international standards."
)

s1_zh = (
    "铁路轨道紧固件系统是保障轨道在极端动载荷条件下保持几何形位、轨距和结构完整性的关键安全部件。现代高速和重载铁路网依赖工程化的扣件组件系统，而非仅依靠传统的道钉。完整的扣件系统通常包括弹性<a href=\"/en/products/track-bolts\" class=\"text-primary-600 hover:text-primary-800 underline\">轨道螺栓</a>、弹簧<a href=\"/en/products/spring-washers\" class=\"text-primary-600 hover:text-primary-800 underline\">弹簧垫圈</a>、绝缘套管、垫板或铁垫板，以及将钢轨底部夹紧到轨枕上的弹性扣件或螺纹道钉。\n\n"
    "三大规范体系主导全球铁路采购：Pandrol e-clip 系统（源自英国，现为 Delachaux 集团旗下）覆盖 80 多个国家，被非洲、中东和亚洲大多数重载铁路网采用。Pandrol Fastclip 和 e-clip 系列在全球拥有最大的装机量。德国制造的 Vossloh 扣件系统通过 Wirthwein 和 Schwihag 子公司供货，主导欧洲高速铁路走廊，包括德铁（DB）、法铁（SNCF）和西班牙国家铁路（RENFE），并通过许可生产越来越多地进入北非、印度和东南亚市场。美国铁路工程与养护协会（AREMA）规范管理北美货运、加拿大国铁（CN）以及墨西哥和中美洲部分地区。\n\n"
    "了解这三个系列之间的差异对服务于跨境招标的采购官员、项目工程师和紧固件贸易商至关重要。混凝土轨枕上典型的公制 Pandrol e-clip（如 e-2055 或 e-2060 系列）单扣件扣压力为 8.8-11.0 kN，而 Vossloh W14 或 Skl14 扣件提供 9-11 kN 的扣压力。AREMA 弹性扣件等效产品如 Safelok I 或 Pandrol PR-clip 系列在 7-10 kN 范围内工作，但采用不同的锚固几何结构。钢轨接头组件使用<a href=\"/en/products/fish-plates\" class=\"text-primary-600 hover:text-primary-800 underline\">鱼尾板</a>（也称为接联板或角板）和<a href=\"/en/products/anchor-bolts\" class=\"text-primary-600 hover:text-primary-800 underline\">地脚螺栓</a>，在无缝线路（CWR）过渡区、绝缘接头位置和桥梁接引处仍然是强制性的，这些位置必须控制钢轨膨胀。\n\n"
    "对于从中国、印度和土耳其采购以服务非洲、中东和拉丁美洲招标的 TradeGo 客户而言，实际影响重大。大多数亚洲和中东铁路当局接受按许可生产的 Pandrol 或 Vossloh 等效产品，通常要求按 EN 13146（欧洲）、UIC 864（国际）或 AREMA 第 5 章（北美）进行第三方测试。最常要求的材料等级是弹性扣件用的 60Si2Mn 或 51CrV4 弹簧钢（抗拉强度 1,200-1,400 MPa），高强度<a href=\"/en/products/hex-nuts\" class=\"text-primary-600 hover:text-primary-800 underline\">轨道螺栓和六角螺母</a>用的 8.8 或 10.9 级，以及垫板和基板用的 Q345B 或 A36 钢。按 EN ISO 1461 的热浸镀锌（涂层厚度 55-85 μm）是热带和沿海网络的默认防腐规范，一些巴西、沙特和澳大利亚招标要求双层环氧面漆以增强耐盐雾性。\n\n"
    "采购量因应用而差异巨大。标准 25 吨集装箱可装载约 80 万个 Pandrol e-clip 或 40 万个 Vossloh Skl 扣件，而 M22×130 mm 或 M24×150 mm 规格的轨道螺栓每集装箱 2.5-3 万件。4 孔或 6 孔配置的鱼尾板每集装箱 8,000-12,000 套，取决于钢轨重量（UIC 54、UIC 60、AREMA 115RE 或 AREMA 136RE）。本文提供采购团队按国际标准规范、采购和检验铁路轨道扣件所需的技术规格、尺寸公差、机械性能和质量控制程序。"
)

s1_es = (
    "Los sistemas de sujetadores de vía férrea son componentes críticos de seguridad que mantienen la alineación, el ancho y la integridad estructural del riel bajo cargas dinámicas extremas. Las redes modernas de alta velocidad y carga pesada dependen de conjuntos de sujeción diseñados en lugar de los tradicionales tirafondos solos. Un sistema completo de sujeción incluye típicamente <a href=\"/en/products/track-bolts\" class=\"text-primary-600 hover:text-primary-800 underline\">pernos de vía</a> elásticos, <a href=\"/en/products/spring-washers\" class=\"text-primary-600 hover:text-primary-800 underline\">arandelas elásticas</a> de resorte, casquillos aislantes, placas de asiento o placas de traviesa, y ya sea clips elásticos o tirafondos que sujetan el pie del riel a la traviesa.\n\n"
    "Tres marcos de especificación dominan la adquisición ferroviaria global: los sistemas Pandrol e-clip (originalmente británicos, ahora parte del Grupo Delachaux) cubren más de 80 países y se especifican en la mayoría de las redes africanas, de Oriente Medio y asiáticas de carga pesada. Los sistemas Vossloh, fabricados en Alemania y suministrados a través de las filiales Wirthwein y Schwihag, dominan los corredores europeos de alta velocidad, incluyendo Deutsche Bahn, SNCF y RENFE, y penetran cada vez más en el norte de África, India y el sudeste asiático a través de producción bajo licencia. La cartera de la American Railway Engineering and Maintenance-of-Way Association (AREMA) rige el transporte de carga norteamericano, Canadian National y partes de México y Centroamérica, con placas de asiento, tirafondos cortados y tirafondos roscados como valores predeterminados tradicionales y clips elásticos ganando terreno en instalaciones modernas de traviesas de hormigón.\n\n"
    "Para los clientes de TradeGo que se abastecen desde China, India y Turquía para licitaciones africanas, de Oriente Medio y latinoamericanas, las implicaciones prácticas son significativas. La mayoría de las autoridades ferroviarias asiáticas y de Oriente Medio aceptan equivalentes Pandrol o Vossloh suministrados bajo licencia, con pruebas de terceros según EN 13146 (Europa), UIC 864 (internacional) o AREMA Capítulo 5 (Norteamérica) típicamente requeridas. Los grados de material más comúnmente solicitados son 60Si2Mn o 51CrV4 para clips elásticos (resistencia a la tracción 1,200-1,400 MPa), Grado 8.8 o 10.9 para <a href=\"/en/products/hex-nuts\" class=\"text-primary-600 hover:text-primary-800 underline\">pernos de vía y tuercas hexagonales</a> de alta resistencia, y Q345B o A36 para placas de asiento y placas base.\n\n"
    "Los volúmenes de adquisición varían dramáticamente según la aplicación. Un contenedor estándar de 25 toneladas carga aproximadamente 800,000 Pandrol e-clips o 400,000 Vossloh Skl clips, mientras que los pernos de vía en tamaños M22 × 130 mm o M24 × 150 mm suman 25,000 a 30,000 piezas por contenedor. Las <a href=\"/en/products/fish-plates\" class=\"text-primary-600 hover:text-primary-800 underline\">placas de empalme</a> (también llamadas barras de unión o barras angulares) en configuraciones de 4 o 6 agujeros empacan 8,000 a 12,000 conjuntos por contenedor dependiendo del peso del riel (UIC 54, UIC 60, AREMA 115RE o AREMA 136RE). Los <a href=\"/en/products/anchor-bolts\" class=\"text-primary-600 hover:text-primary-800 underline\">pernos de anclaje</a> siguen siendo obligatorios en zonas de transición de riel soldado continuo (CWR), ubicaciones de juntas aisladas y en acercamientos a puentes donde la expansión del riel debe controlarse."
)

s1_ar = (
    "تعد أنظمة مثبتات مسارات السكك الحديدية مكونات أمان حرجة تحافظ على محاذاة السكة وقياس المسار والسلامة الهيكلية تحت الأحمال الديناميكية القصوى. تعتمد شبكات النقل الحديثة عالية السرعة والثقيلة على مجموعات تثبيت هندسية بدلاً من مسامير السكك التقليدية وحدها. يتضمن نظام التثبيت الكامل عادةً <a href=\"/en/products/track-bolts\" class=\"text-primary-600 hover:text-primary-800 underline\">مسامير مسار</a> مرنة، و<a href=\"/en/products/spring-washers\" class=\"text-primary-600 hover:text-primary-800 underline\">حلقات زنبركية</a>، وبطانات عازلة، وألواح قاعدة أو ألواح ربط، ومشبكات مرنة أو مسامير لولبية تثبت قدم السكة على النائمة.\n\n"
    "تسيطر ثلاثة أطر للمواصفات على المشتريات العالمية للسكك الحديدية: تغطي أنظمة Pandrol e-clip (بريطانية الأصل، وهي الآن جزء من مجموعة Delachaux) أكثر من 80 دولة. تهيمن أنظمة Vossloh، المصنعة في ألمانيا والموردة من خلال الشركات التابعة Wirthwein وSchwihag، على ممرات السرعة العالية الأوروبية. تحكم محفظة الجمعية الأمريكية لهندسة وصيانة السكك الحديدية (AREMA) الشحن في أمريكا الشمالية.\n\n"
    "بالنسبة لعملاء TradeGo الذين يحصلون على الإمدادات من الصين والهند وتركيا للمناقصات الأفريقية والشرق أوسطية وأمريكا اللاتينية، فإن الآثار العملية كبيرة. تقبل معظم هيئات السكك الحديدية الآسيوية والشرق أوسطية مكافئات Pandrol أو Vossloh الموردة بموجب ترخيص، مع الاختبار من طرف ثالث وفقًا لـ EN 13146 أو UIC 864 أو AREMA الفصل 5.\n\n"
    "تختلف أحجام المشتريات بشكل كبير حسب التطبيق. يقوم حاوية قياسية سعة 25 طنًا بتحميل ما يقرب من 800,000 Pandrol e-clips أو 400,000 Vossloh Skl clips. تحزم <a href=\"/en/products/fish-plates\" class=\"text-primary-600 hover:text-primary-800 underline\">صفائح السمك</a> (تسمى أيضًا قضبان الوصل أو القضبان الزاوية) في تكوينات 4 أو 6 فتحات من 8,000 إلى 12,000 مجموعة لكل حاوية."
)

s1_fr = (
    "Les systèmes d'attaches ferroviaires sont des composants de sécurité critiques qui maintiennent l'alignement, l'écartement et l'intégrité structurelle du rail sous des charges dynamiques extrêmes. Les réseaux modernes à grande vitesse et à fort tonnage dépendent d'ensembles de fixation conçus plutôt que des seuls crampons traditionnels. Un système de fixation complet comprend généralement des <a href=\"/en/products/track-bolts\" class=\"text-primary-600 hover:text-primary-800 underline\">boulons de voie</a> élastiques, des <a href=\"/en/products/spring-washers\" class=\"text-primary-600 hover:text-primary-800 underline\">rondelles élastiques</a>, des douilles isolantes, des plaques d'assise ou des semelles, et soit des clips élastiques soit des crampons qui serrent le patin du rail sur la traverse.\n\n"
    "Trois cadres de spécifications dominent l'approvisionnement ferroviaire mondial : les systèmes Pandrol e-clip (à l'origine britanniques, maintenant partie du Groupe Delachaux) couvrent plus de 80 pays. Les systèmes Vossloh, fabriqués en Allemagne et fournis par les filiales Wirthwein et Schwihag, dominent les corridors européens à grande vitesse. Le portefeuille de l'American Railway Engineering and Maintenance-of-Way Association (AREMA) régit le fret nord-américain.\n\n"
    "Pour les clients TradeGo s'approvisionnant en Chine, en Inde et en Turquie pour les appels d'offres africains, du Moyen-Orient et latino-américains, les implications pratiques sont significatives. La plupart des autorités ferroviaires asiatiques et du Moyen-Orient acceptent les équivalents Pandrol ou Vossloh fournis sous licence, avec des tests tiers selon EN 13146, UIC 864 ou AREMA Chapitre 5.\n\n"
    "Les volumes d'approvisionnement varient considérablement selon l'application. Un conteneur standard de 25 tonnes charge environ 800 000 Pandrol e-clips ou 400 000 clips Vossloh Skl, tandis que les boulons de voie en tailles M22 × 130 mm ou M24 × 150 mm vont de 25 000 à 30 000 pièces par conteneur. Les <a href=\"/en/products/fish-plates\" class=\"text-primary-600 hover:text-primary-800 underline\">éclisses</a> (également appelées barres de joint ou barres angulaires) dans des configurations à 4 ou 6 trous contiennent 8 000 à 12 000 ensembles par conteneur."
)

s1_pt = (
    "Os sistemas de fixadores de trilhos ferroviários são componentes críticos de segurança que mantêm o alinhamento do trilho, a bitola e a integridade estrutural sob cargas dinâmicas extremas. As redes modernas de alta velocidade e carga pesada dependem de conjuntos de fixação projetados em vez de apenas tirefundos tradicionais. Um sistema completo inclui tipicamente <a href=\"/en/products/track-bolts\" class=\"text-primary-600 hover:text-primary-800 underline\">parafusos de via</a> elásticos, <a href=\"/en/products/spring-washers\" class=\"text-primary-600 hover:text-primary-800 underline\">arruelas de pressão</a>, buchas isolantes, placas de base ou placas de dormente, e clipes elásticos ou parafusos que prendem o pé do trilho ao dormente.\n\n"
    "Três estruturas de especificação dominam as aquisições ferroviárias globais: os sistemas Pandrol e-clip (originalmente britânicos, agora parte do Grupo Delachaux) cobrem mais de 80 países. Os sistemas Vossloh, fabricados na Alemanha e fornecidos pelas subsidiárias Wirthwein e Schwihag, dominam os corredores europeus de alta velocidade. O portfólio da American Railway Engineering and Maintenance-of-Way Association (AREMA) rege o frete norte-americano.\n\n"
    "Para os clientes da TradeGo que se abastecem na China, Índia e Turquia para licitações africanas, do Oriente Médio e latino-americanas, as implicações práticas são significativas. A maioria das autoridades ferroviárias asiáticas e do Oriente Médio aceitam equivalentes Pandrol ou Vossloh fornecidos sob licença, com testes de terceiros conforme EN 13146, UIC 864 ou AREMA Capítulo 5.\n\n"
    "Os volumes de aquisição variam drasticamente conforme a aplicação. Um contêiner padrão de 25 toneladas carrega aproximadamente 800.000 Pandrol e-clips ou 400.000 Vossloh Skl clips. As <a href=\"/en/products/fish-plates\" class=\"text-primary-600 hover:text-primary-800 underline\">talas de junção</a> (também chamadas barras de junção) em configurações de 4 ou 6 furos embalam 8.000 a 12.000 conjuntos por contêiner."
)

s1_ru = (
    "Системы крепежа железнодорожных путей являются критически важными компонентами безопасности, которые поддерживают выравнивание рельсов, ширину колеи и структурную целостность при экстремальных динамических нагрузках. Современные высокоскоростные и тяжеловесные сети зависят от спроектированных узлов крепления, а не только от традиционных костылей. Полная система крепления обычно включает эластичные <a href=\"/en/products/track-bolts\" class=\"text-primary-600 hover:text-primary-800 underline\">путевые болты</a>, <a href=\"/en/products/spring-washers\" class=\"text-primary-600 hover:text-primary-800 underline\">пружинные шайбы</a>, изолирующие втулки, подкладки или подрельсовые прокладки, и либо упругие зажимы, либо шурупы-костыли, которые зажимают подошву рельса к шпале.\n\n"
    "Три системы спецификаций доминируют в мировых железнодорожных закупках: системы Pandrol e-clip (изначально британские, теперь часть группы Delachaux) охватывают более 80 стран. Системы Vossloh, производимые в Германии и поставляемые через дочерние компании Wirthwein и Schwihag, доминируют на европейских высокоскоростных коридорах. Портфолио Американской ассоциации железнодорожного машиностроения и путевого хозяйства (AREMA) регулирует североамериканские грузовые перевозки.\n\n"
    "Для клиентов TradeGo, закупающих продукцию в Китае, Индии и Турции для африканских, ближневосточных и латиноамериканских тендеров, практические последствия значительны. Большинство азиатских и ближневосточных железнодорожных ведомств принимают эквиваленты Pandrol или Vossloh, поставляемые по лицензии, со сторонними испытаниями по EN 13146, UIC 864 или AREMA Глава 5.\n\n"
    "Объемы закупок значительно варьируются в зависимости от применения. Стандартный 25-тонный контейнер вмещает приблизительно 800 000 Pandrol e-clips или 400 000 Vossloh Skl clips. <a href=\"/en/products/fish-plates\" class=\"text-primary-600 hover:text-primary-800 underline\">Стыковые накладки</a> (также называемые соединительными или угловыми планками) в 4- или 6-дырочной конфигурации упаковывают 8 000–12 000 комплектов на контейнер."
)

s1_ja = (
    "鉄道軌道締結システムは、極限の動的荷重下でレールの位置、軌間、構造的完全性を維持する重要な安全部品です。現代的な高速・重荷重鉄道網は、従来の犬釘だけでなく、エンジニアリングされた締結アセンブリに依存しています。完全な締結システムは通常、弾性<a href=\"/en/products/track-bolts\" class=\"text-primary-600 hover:text-primary-800 underline\">軌道ボルト</a>、<a href=\"/en/products/spring-washers\" class=\"text-primary-600 hover:text-primary-800 underline\">スプリングワッシャー</a>、絶縁ブッシュ、ベースプレートまたはタイプレート、およびレール底部を枕木にクランプする弾性クリップまたはネジスパイクを含みます。\n\n"
    "3つの仕様枠組みが世界の鉄道調達を支配しています。Pandrol e-clip システム（元々英国製、現在は Delachaux グループの一部）は 80 か国以上をカバーしています。Vossloh システムはドイツで製造され、子会社の Wirthwein と Schwihag を通じて供給され、欧州の高速回廊を支配しています。アメリカ鉄道工学・保守協会 (AREMA) のポートフォリオは北米の貨物を管理しています。\n\n"
    "アフリカ、中東、ラテンアメリカの入札のために中国、インド、トルコから調達する TradeGo の顧客にとって、実際的な影響は重要です。アジアと中東のほとんどの鉄道当局は、ライセンス供与された Pandrol または Vossloh 相当品を受け入れ、EN 13146、UIC 864、または AREMA 第 5 章に基づく第三者試験を必要とします。\n\n"
    "調達量は用途によって大きく異なります。標準的な 25 トンコンテナには約 80 万個の Pandrol e-clip または 40 万個の Vossloh Skl clip が積載されます。<a href=\"/en/products/fish-plates\" class=\"text-primary-600 hover:text-primary-800 underline\">フィッシュプレート</a>（継目板またはアングルバーとも呼ばれる）は、4 穴または 6 穴構成で、コンテナあたり 8,000〜12,000 セットを梱包します。"
)

s1_de = (
    "Eisenbahnschienen-Befestigungssysteme sind kritische Sicherheitskomponenten, die die Schienenausrichtung, Spurweite und strukturelle Integrität unter extremen dynamischen Belastungen aufrechterhalten. Moderne Hochgeschwindigkeits- und Schwerlastnetze sind auf konstruierte Befestigungsbaugruppen angewiesen, nicht nur auf traditionelle Schienennägel. Ein komplettes Befestigungssystem umfasst typischerweise elastische <a href=\"/en/products/track-bolts\" class=\"text-primary-600 hover:text-primary-800 underline\">Schienenschrauben</a>, <a href=\"/en/products/spring-washers\" class=\"text-primary-600 hover:text-primary-800 underline\">Federringe</a>, Isolierbuchsen, Grundplatten oder Schwellenplatten und entweder elastische Clips oder Schraubenspitzen, die den Schienenfuß an der Schwelle festklemmen.\n\n"
    "Drei Spezifikationsrahmen dominieren die globale Eisenbahnbeschaffung: Pandrol e-clip-Systeme (ursprünglich britisch, jetzt Teil der Delachaux-Gruppe) decken mehr als 80 Länder ab. Vossloh-Systeme, hergestellt in Deutschland und geliefert durch die Tochtergesellschaften Wirthwein und Schwihag, dominieren europäische Hochgeschwindigkeitskorridore. Das Portfolio der American Railway Engineering and Maintenance-of-Way Association (AREMA) regelt den nordamerikanischen Güterverkehr.\n\n"
    "Für TradeGo-Kunden, die aus China, Indien und der Türkei für afrikanische, nahöstliche und lateinamerikanische Ausschreibungen beschaffen, sind die praktischen Auswirkungen erheblich. Die meisten asiatischen und nahöstlichen Eisenbahnbehörden akzeptieren lizenzierte Pandrol- oder Vossloh-Äquivalente, mit Drittrüferprüfung nach EN 13146, UIC 864 oder AREMA Kapitel 5.\n\n"
    "Die Beschaffungsmengen variieren je nach Anwendung drastisch. Ein Standard-25-Tonnen-Container lädt ungefähr 800.000 Pandrol e-clips oder 400.000 Vossloh Skl-Clips. <a href=\"/en/products/fish-plates\" class=\"text-primary-600 hover:text-primary-800 underline\">Laschen</a> (auch Stoßlaschen oder Winkelstangen genannt) in 4- oder 6-Loch-Konfigurationen packen 8.000 bis 12.000 Sätze pro Container."
)

s1_hi = (
    "रेलवे ट्रैक फास्टनर सिस्टम महत्वपूर्ण सुरक्षा घटक हैं जो चरम गतिशील भार के तहत रेल संरेखण, गेज और संरचनात्मक अखंडता बनाए रखते हैं। आधुनिक हाई-स्पीड और भारी-हॉल नेटवर्क पारंपरिक रेल स्पाइक्स के बजाय इंजीनियर फास्टनिंग असेंबली पर निर्भर करते हैं। एक पूर्ण फास्टनिंग सिस्टम में आमतौर पर लोचदार <a href=\"/en/products/track-bolts\" class=\"text-primary-600 hover:text-primary-800 underline\">ट्रैक बोल्ट्स</a>, <a href=\"/en/products/spring-washers\" class=\"text-primary-600 hover:text-primary-800 underline\">स्प्रिंग वॉशर</a>, इन्सुलेटिंग बुशिंग, बेसप्लेट या टाई प्लेट्स, और या तो लोचदार क्लिप या स्क्रू स्पाइक्स होते हैं जो रेल पैर को स्लीपर पर क्लैम्प करते हैं।\n\n"
    "तीन विशिष्टता ढांचे वैश्विक रेलवे खरीद पर हावी हैं: Pandrol e-clip सिस्टम (मूल रूप से ब्रिटिश, अब Delachaux Group का हिस्सा) 80 से अधिक देशों को कवर करते हैं। जर्मनी में निर्मित Vossloh सिस्टम, सहायक कंपनियों Wirthwein और Schwihag के माध्यम से आपूर्ति, यूरोपीय हाई-स्पीड कॉरिडोर पर हावी हैं। अमेरिकन रेलवे इंजीनियरिंग एंड मेंटेनेंस-ऑफ-वे एसोसिएशन (AREMA) पोर्टफोलियो उत्तरी अमेरिकी माल पर शासन करता है।\n\n"
    "अफ्रीकी, मध्य पूर्व और लैटिन अमेरिकी निविदाओं के लिए चीन, भारत और तुर्की से सोर्सिंग करने वाले TradeGo ग्राहकों के लिए, व्यावहारिक प्रभाव महत्वपूर्ण हैं। अधिकांश एशियाई और मध्य पूर्व रेलवे अधिकारी लाइसेंस के तहत आपूर्ति किए गए Pandrol या Vossloh समकक्ष स्वीकार करते हैं, EN 13146, UIC 864, या AREMA अध्याय 5 के अनुसार तीसरे पक्ष के परीक्षण की आवश्यकता होती है।\n\n"
    "खरीद मात्रा अनुप्रयोग के अनुसार नाटकीय रूप से भिन्न होती है। एक मानक 25-टन कंटेनर लगभग 800,000 Pandrol e-clips या 400,000 Vossloh Skl clips लोड करता है। <a href=\"/en/products/fish-plates\" class=\"text-primary-600 hover:text-primary-800 underline\">फिश प्लेट्स</a> (जॉइंट बार या एंगल बार भी कहा जाता है) 4-छिद्र या 6-छिद्र कॉन्फ़िगरेशन में 8,000 से 12,000 सेट प्रति कंटेनर पैक करते हैं।"
)

s1_body = t(s1_en, s1_zh, s1_es, s1_ar, s1_fr, s1_pt, s1_ru, s1_ja, s1_de, s1_hi)


# Section 2: Pandrol
s2_heading = t(
    "Pandrol E-Clip and Fastclip Specifications",
    "Pandrol E-Clip 和 Fastclip 规格",
    "Especificaciones Pandrol E-Clip y Fastclip",
    "مواصفات Pandrol E-Clip و Fastclip",
    "Spécifications Pandrol E-Clip et Fastclip",
    "Especificações Pandrol E-Clip e Fastclip",
    "Спецификации Pandrol E-Clip и Fastclip",
    "Pandrol E-Clip および Fastclip 仕様",
    "Pandrol e-Clip und Fastclip Spezifikationen",
    "Pandrol e-Clip और Fastclip विशिष्टताएं"
)

s2_en = (
    "The Pandrol e-clip family is the most widely installed elastic rail clip in the world, with production capacity exceeding 60 million clips per year across facilities in the United Kingdom, France, China (Shanghai and Suzhou), India, and the United States. The original e-clip, patented in 1957 by the late inventor Per Pétersen, derives its name from its distinctive E-shaped cross-section that wraps around the rail foot and is dynamically loaded by a cast shoulder inserted into the concrete sleeper. The current generation includes the e-2055 (for 60 kg/m rail), e-2060 (for AREMA 115RE/136RE rail), e-2009 (heavy-haul high-stress), and the e-2080 (light-rail and tram applications).\n\n"
    "Dimensional and mechanical specifications for the most common e-clip variants are tightly controlled by Pandrol's proprietary drawings and are subject to third-party verification under EN 13146-5 (longitudinal rail restraint test) and EN 13146-4 (repeated load test). Typical values: e-2055 nominal diameter 20 mm, free height 80 mm, toe load at 12 mm deflection of 8.8-9.5 kN per clip, fatigue life exceeding 5 million cycles at ±1.0 mm deflection amplitude. Material is hot-rolled spring steel per EN 10089 grade 60SiCr7 or 51CrV4 (tensile strength 1,400-1,600 MPa, hardness 44-48 HRC after heat treatment), with surface shot-peening per EN 25714 to introduce compressive residual stress that extends fatigue life by 30-50%.\n\n"
    "The Pandrol Fastclip system, introduced in the 1990s and now the default for new-build high-speed and heavy-haul installations, replaces the cast shoulder with a pre-installed plastic or metal insert that allows the clip to be installed or removed with a simple hand tool in 3-5 seconds. The FC-1500 (for 60 kg/m rail) and FC-1600 (for 50 kg/m rail) variants are the most common, with the FC-Pandrol HD variant for 32.5-tonne axle-load heavy-haul mining railways. Fastclip fasteners allow maintenance crews to replace clips without breaking concrete, reducing track possession time by 60-80% compared with e-clip systems. The patented installation procedure requires a calibrated hydraulic or mechanical applicator to set the correct toe load and confirm clip seating.\n\n"
    "For the African and Middle Eastern markets served by TradeGo, third-party-manufactured Pandrol-equivalent clips are common, and most tenders accept equivalents that pass the following key tests: (1) static toe load within ±10% of nominal 8.8 kN at 12 mm deflection, (2) dynamic stiffness between 50 and 90 kN/mm, (3) creep resistance less than 1.0 mm at 25,000 cycles under ±1.0 mm deflection, (4) salt-spray corrosion resistance exceeding 1,000 hours per ASTM B117 with red rust less than 5% surface area, and (5) electrical resistance exceeding 5 kΩ when used with nylon insulator. Material certificates (EN 10204 3.1 or 3.2) must accompany each shipment, and pre-shipment inspections by SGS, Bureau Veritas, or Intertek are typically required for contracts above USD 200,000.\n\n"
    "A common specification callout for a Pandrol e-2055 equivalent supplied to an African tender reads: 'Elastic rail clip, hot-rolled spring steel grade 60SiCr7, dimensions per Pandrol drawing 2055, toe load 8.8-9.5 kN at 12 mm deflection, fatigue life 5 million cycles minimum, surface shot-peened, phosphate or Delta Tone coating, packaged 200 pieces per steel-strapped plywood crate, suitable for 60 kg/m UIC rail on B70 concrete sleeper.' This level of detail eliminates ambiguity and protects both buyer and supplier during quality disputes."
)

s2_zh = (
    "Pandrol e-clip 系列是全球安装最广泛的弹性轨道扣件，年产能超过 6,000 万件，分布在英国、法国、中国（上海和苏州）、印度和美国的工厂。原始 e-clip 由已故发明家 Per Pétersen 于 1957 年获得专利，其名称源自其独特的 E 形截面，可环绕钢轨底部并通过嵌入混凝土轨枕的铸造肩部动态加载。当代产品包括 e-2055（用于 60 kg/m 钢轨）、e-2060（用于 AREMA 115RE/136RE 钢轨）、e-2009（重载高应力）和 e-2080（轻轨和电车应用）。\n\n"
    "最常见 e-clip 变体的尺寸和机械规格由 Pandrol 的专有图纸严格控制，并需按 EN 13146-5（纵向钢轨约束试验）和 EN 13146-4（重复载荷试验）进行第三方验证。典型值：e-2055 标称直径 20 mm，自由高度 80 mm，12 mm 挠度时单扣件扣压力 8.8-9.5 kN，±1.0 mm 挠度幅值下疲劳寿命超过 500 万次。材料按 EN 10089 标准 60SiCr7 或 51CrV4 热轧弹簧钢（抗拉强度 1,400-1,600 MPa，热处理后硬度 44-48 HRC），并按 EN 25714 进行表面喷丸以引入压残余应力，将疲劳寿命延长 30-50%。\n\n"
    "Pandrol Fastclip 系统于 1990 年代推出，是新建高速和重载铁路的默认配置，它用预安装的塑料或金属嵌件替代了铸造肩部，允许使用简单的手工工具在 3-5 秒内安装或拆卸扣件。FC-1500（用于 60 kg/m 钢轨）和 FC-1600（用于 50 kg/m 钢轨）变体最为常见，FC-Pandrol HD 变体用于 32.5 吨轴重重载矿山铁路。Fastclip 紧固件使维护团队能够在不破坏混凝土的情况下更换扣件，与 e-clip 系统相比，轨道占用时间减少 60-80%。\n\n"
    "对于 TradeGo 服务的非洲和中东市场，第三方制造的 Pandrol 等效扣件很常见，大多数招标接受通过以下关键试验的等效产品：(1) 静态扣压力在标称 8.8 kN 的 ±10% 范围内，挠度 12 mm；(2) 动态刚度在 50-90 kN/mm 之间；(3) 在 ±1.0 mm 挠度下 25,000 次循环的蠕变抗力小于 1.0 mm；(4) 盐雾耐腐蚀性超过 1,000 小时符合 ASTM B117，红锈少于 5% 表面区域；(5) 与尼龙绝缘体一起使用时的电阻超过 5 kΩ。\n\n"
    "对于供应到非洲招标的 Pandrol e-2055 等效产品的常见规范说明为：'弹性轨道扣件，热轧弹簧钢等级 60SiCr7，尺寸按 Pandrol 图纸 2055，12 mm 挠度时扣压力 8.8-9.5 kN，疲劳寿命最少 500 万次，表面喷丸，磷酸盐或 Delta Tone 涂层，每 200 件一箱用钢条捆扎的胶合板箱包装，适用于 60 kg/m UIC 钢轨在 B70 混凝土轨枕上。' 这种详细程度消除了歧义，并在质量争议中保护买卖双方。"
)

s2_es = (
    "La familia Pandrol e-clip es el clip elástico de riel más ampliamente instalado en el mundo, con una capacidad de producción que supera los 60 millones de clips por año en instalaciones en el Reino Unido, Francia, China, India y Estados Unidos. El e-clip original, patentado en 1957, debe su nombre a su distintiva sección transversal en forma de E que envuelve el pie del riel y se carga dinámicamente mediante un hombro fundido insertado en la traviesa de hormigón.\n\n"
    "Las especificaciones dimensionales y mecánicas para las variantes e-clip más comunes están estrictamente controladas por los planos propietarios de Pandrol y están sujetas a verificación de terceros según EN 13146-5 y EN 13146-4. Valores típicos: e-2055 diámetro nominal 20 mm, altura libre 80 mm, carga de la punta 8.8-9.5 kN por clip a 12 mm de deflexión, vida de fatiga que excede 5 millones de ciclos.\n\n"
    "El sistema Pandrol Fastclip, introducido en la década de 1990 y ahora el predeterminado para instalaciones nuevas de alta velocidad y carga pesada, reemplaza el hombro fundido con un inserto plástico o metálico preinstalado que permite instalar o quitar el clip con una simple herramienta manual en 3-5 segundos. Las variantes FC-1500 y FC-1600 son las más comunes, con la variante FC-Pandrol HD para ferrocarriles mineros de 32,5 toneladas por eje.\n\n"
    "Para los mercados africanos y de Oriente Medio servidos por TradeGo, los clips equivalentes Pandrol fabricados por terceros son comunes, y la mayoría de las licitaciones aceptan equivalentes que pasen las siguientes pruebas clave: (1) carga de punta estática dentro de ±10% del nominal 8.8 kN a 12 mm de deflexión, (2) rigidez dinámica entre 50 y 90 kN/mm, (3) resistencia a la fluencia menor a 1.0 mm en 25,000 ciclos bajo deflexión de ±1.0 mm."
)

s2_ar = (
    "عائلة Pandrol e-clip هي أكثر مقاطع السكك المرنة تثبيتا في العالم، مع قدرة إنتاجية تتجاوز 60 مليون مقطع سنويًا عبر منشآت في المملكة المتحدة وفرنسا والصين والهند والولايات المتحدة. حصل e-clip الأصلي، الذي تم تسجيل براءة اختراعه في عام 1957، على اسمه من مقطعه العرضي المميز على شكل E الذي يلتف حول قدم السكة ويتم تحميله ديناميكيًا بواسطة كتف مصبوب مدرج في النائمة الخرسانية.\n\n"
    "للأسواق الأفريقية والشرق أوسطية التي تخدمها TradeGo، تعتبر مقاطع Pandrol المكافئة المصنعة من قبل طرف ثالث شائعة، ومعظم المناقصات تقبل المكافئات التي تجتاز الاختبارات الرئيسية التالية: (1) حمل نقطة ثابت في حدود ±10% من 8.8 kN الاسمي عند انحراف 12 mm، (2) صلابة ديناميكية بين 50 و90 kN/mm، (3) مقاومة الزحف أقل من 1.0 mm عند 25,000 دورة تحت انحراف ±1.0 mm."
)

s2_fr = (
    "La famille Pandrol e-clip est le clip élastique de rail le plus largement installé au monde, avec une capacité de production dépassant 60 millions de clips par an dans des installations au Royaume-Uni, en France, en Chine, en Inde et aux États-Unis. Le e-clip original, breveté en 1957, tire son nom de sa section transversale distinctive en forme de E qui enveloppe le patin du rail et est chargé dynamiquement par un épaule moulée insérée dans la traverse en béton.\n\n"
    "Les spécifications dimensionnelles et mécaniques pour les variantes e-clip les plus courantes sont étroitement contrôlées par les dessins propriétaires de Pandrol et sont soumises à une vérification par des tiers selon EN 13146-5 et EN 13146-4. Valeurs typiques : e-2055 diamètre nominal 20 mm, hauteur libre 80 mm, charge de pointe 8,8-9,5 kN par clip à 12 mm de déflexion, durée de vie en fatigue dépassant 5 millions de cycles.\n\n"
    "Pour les marchés africains et du Moyen-Orient desservis par TradeGo, les clips équivalents Pandrol fabriqués par des tiers sont courants, et la plupart des appels d'offres acceptent des équivalents qui passent les tests clés suivants : (1) charge de pointe statique dans les ±10% du nominal 8,8 kN à 12 mm de déflexion, (2) rigidité dynamique entre 50 et 90 kN/mm, (3) résistance au fluage inférieure à 1,0 mm à 25 000 cycles."
)

s2_pt = (
    "A família Pandrol e-clip é o clipe elástico de trilho mais amplamente instalado no mundo, com capacidade de produção excedendo 60 milhões de clipes por ano em instalações no Reino Unido, França, China, Índia e Estados Unidos. O e-clip original, patenteado em 1957, deve seu nome à sua distinta seção transversal em forma de E que envolve o pé do trilho e é carregado dinamicamente por um ombro fundido inserido no dormente de concreto.\n\n"
    "As especificações dimensionais e mecânicas para as variantes e-clip mais comuns são estritamente controladas pelos desenhos proprietários da Pandrol e estão sujeitas à verificação de terceiros sob EN 13146-5 e EN 13146-4. Valores típicos: e-2055 diâmetro nominal 20 mm, altura livre 80 mm, carga da ponta 8,8-9,5 kN por clipe a 12 mm de deflexão, vida de fadiga excedendo 5 milhões de ciclos.\n\n"
    "Para os mercados africanos e do Oriente Médio atendidos pela TradeGo, clipes Pandrol equivalentes fabricados por terceiros são comuns, e a maioria das licitações aceita equivalentes que passem nos seguintes testes principais: (1) carga estática da ponta dentro de ±10% do nominal 8,8 kN a 12 mm de deflexão, (2) rigidez dinâmica entre 50 e 90 kN/mm, (3) resistência à fluência menor que 1,0 mm a 25.000 ciclos."
)

s2_ru = (
    "Семейство Pandrol e-clip является наиболее широко установленным упругим рельсовым зажимом в мире, с производственной мощностью, превышающей 60 миллионов зажимов в год на предприятиях в Великобритании, Франции, Китае, Индии и США. Оригинальный e-clip, запатентованный в 1957 году, получил свое название благодаря характерному поперечному сечению в форме буквы E, которое охватывает подошву рельса и динамически нагружается литым буртом, вставленным в бетонную шпалу.\n\n"
    "Размерные и механические спецификации для наиболее распространенных вариантов e-clip строго контролируются патентованными чертежами Pandrol и подлежат сторонней проверке по EN 13146-5 и EN 13146-4. Типичные значения: e-2055 номинальный диаметр 20 мм, свободная высота 80 мм, нагрузка на носке 8,8-9,5 кН на зажим при прогибе 12 мм, усталостная долговечность более 5 миллионов циклов.\n\n"
    "Для африканских и ближневосточных рынков, обслуживаемых TradeGo, широко распространены эквивалентные зажимы Pandrol, изготовленные сторонними производителями, и большинство тендеров принимают эквиваленты, проходящие следующие ключевые испытания: (1) статическая нагрузка на носке в пределах ±10% от номинала 8,8 кН при прогибе 12 мм, (2) динамическая жесткость от 50 до 90 кН/мм, (3) сопротивление ползучести менее 1,0 мм при 25 000 циклов."
)

s2_ja = (
    "Pandrol e-clip ファミリーは、世界で最も広く設置されている弾性レールクリップであり、英国、フランス、中国、インド、米国の製造施設で年間 6,000 万個を超える生産能力を持っています。1957 年に特許を取得したオリジナルの e-clip は、その特徴的な E 字型断面に由来し、レール底部を包み込み、コンクリート枕木に挿入された鋳造ショルダーによって動的に荷重されます。\n\n"
    "最も一般的な e-clip バリアントの寸法および機械的仕様は、Pandrol 独自の図面によって厳密に管理され、EN 13146-5 および EN 13146-4 に基づく第三者検証の対象となります。典型的な値：e-2055 公称直径 20 mm、自由高さ 80 mm、12 mm 撓み時のクリップあたり爪先荷重 8.8-9.5 kN、500 万サイクルを超える疲労寿命。\n\n"
    "TradeGo がサービスを提供するアフリカおよび中東市場では、第三者製造の Pandrol 相当クリップが一般的であり、ほとんどの入札は次の主要な試験に合格する同等品を受け入れます：(1) 12 mm 撓み時の公称 8.8 kN の ±10% 以内の静的爪先荷重、(2) 50〜90 kN/mm の動的剛性、(3) ±1.0 mm 撓み下で 25,000 サイクル時に 1.0 mm 未満のクリープ抵抗。"
)

s2_de = (
    "Die Pandrol e-clip-Familie ist der am weitesten verbreitete elastische Schienenclip der Welt, mit einer Produktionskapazität von über 60 Millionen Clips pro Jahr in Werken in Großbritannien, Frankreich, China, Indien und den USA. Der originale e-clip, 1957 patentiert, verdankt seinen Namen seinem markanten E-förmigen Querschnitt, der den Schienenfuß umschließt und dynamisch durch eine in die Betonschwelle eingesetzte Gussschulter belastet wird.\n\n"
    "Dimensions- und mechanische Spezifikationen für die gängigsten e-clip-Varianten werden streng durch Pandrol-eigene Zeichnungen kontrolliert und unterliegen einer Drittrüferprüfung nach EN 13146-5 und EN 13146-4. Typische Werte: e-2055 Nenndurchmesser 20 mm, freie Höhe 80 mm, Spitzenlast 8,8-9,5 kN pro Clip bei 12 mm Durchbiegung, Ermüdungslebensdauer über 5 Millionen Zyklen.\n\n"
    "Für die von TradeGo bedienten afrikanischen und nahöstlichen Märkte sind Pandrol-Äquivalente von Drittherstellern üblich, und die meisten Ausschreibungen akzeptieren Äquivalente, die die folgenden Schlüsselprüfungen bestehen: (1) statische Spitzenlast innerhalb von ±10% des Nennwerts 8,8 kN bei 12 mm Durchbiegung, (2) dynamische Steifigkeit zwischen 50 und 90 kN/mm, (3) Kriechfestigkeit weniger als 1,0 mm bei 25.000 Zyklen."
)

s2_hi = (
    "Pandrol e-clip परिवार दुनिया में सबसे व्यापक रूप से स्थापित लोचदार रेल क्लिप है, जिसकी उत्पादन क्षमता यूनाइटेड किंगडम, फ्रांस, चीन, भारत और अमेरिका में सुविधाओं में प्रति वर्ष 60 मिलियन क्लिप्स से अधिक है। 1957 में पेटेंट किया गया मूल e-clip अपने विशिष्ट E-आकार के क्रॉस-सेक्शन से अपना नाम लेता है जो रेल पैर को लपेटता है और कंक्रीट स्लीपर में डाले गए कास्ट शोल्डर द्वारा गतिशील रूप से भारित होता है।\n\n"
    "सबसे सामान्य e-clip विविधताओं के लिए आयामी और यांत्रिक विशिष्टताएं Pandrol के मालिकाना चित्रों द्वारा कड़ाई से नियंत्रित होती हैं और EN 13146-5 और EN 13146-4 के तहत तीसरे पक्ष के सत्यापन के अधीन हैं। विशिष्ट मान: e-2055 नाममात्र व्यास 20 mm, मुक्त ऊंचाई 80 mm, 12 mm विक्षेपण पर क्लिप प्रति पैर की उंगली भार 8.8-9.5 kN, 5 मिलियन चक्र से अधिक थकान जीवन।\n\n"
    "TradeGo द्वारा सेवित अफ्रीकी और मध्य पूर्व बाजारों के लिए, तीसरे पक्ष द्वारा निर्मित Pandrol समकक्ष क्लिप्स सामान्य हैं, और अधिकांश निविदाएं निम्नलिखित प्रमुख परीक्षणों को पास करने वाले समकक्षों को स्वीकार करती हैं: (1) 12 mm विक्षेपण पर नाममात्र 8.8 kN के ±10% के भीतर स्थैतिक पैर की उंगली भार, (2) 50 और 90 kN/mm के बीच गतिशील कठोरता, (3) ±1.0 mm विक्षेपण के तहत 25,000 चक्र पर 1.0 mm से कम क्रीप प्रतिरोध।"
)

s2_body = t(s2_en, s2_zh, s2_es, s2_ar, s2_fr, s2_pt, s2_ru, s2_ja, s2_de, s2_hi)


# Section 3: Vossloh
s3_heading = t(
    "Vossloh Skl, W, and DFF Series Specifications",
    "Vossloh Skl、W 和 DFF 系列规格",
    "Especificaciones Vossloh Series Skl, W y DFF",
    "مواصفات سلسلة Vossloh Skl وW وDFF",
    "Spécifications Vossloh Séries Skl, W et DFF",
    "Especificações Vossloh Séries Skl, W e DFF",
    "Спецификации Vossloh серий Skl, W и DFF",
    "Vossloh Skl、W、DFF シリーズ仕様",
    "Vossloh Skl, W und DFF Serienspezifikationen",
    "Vossloh Skl, W और DFF सीरीज़ विशिष्टताएं"
)

s3_en = (
    "Vossloh fastening systems, engineered in Werdohl, Germany, and now consolidated under the Vossloh AG rail infrastructure division, set the global benchmark for high-speed rail fastening performance. The Vossloh product hierarchy begins with the Skl tension clamp (Spannklemme), which has dominated European heavy-haul and high-speed applications since the 1970s. The Skl 14 is the workhorse for ballasted track at speeds up to 250 km/h, the Skl 21 covers heavy-haul freight up to 32.5-tonne axle loads, and the Skl 24 / Skl 30 series are reserved for high-speed corridors above 250 km/h where dynamic uplift forces from pantograph-aerodynamic interaction can reach 30 kN per axle.\n\n"
    "A Vossloh Skl 14 system comprises four primary components: (1) the Skl 14 tension clamp itself, a 3 mm-thick hot-rolled spring steel stamping with a 14 mm diameter wire cross-section and toe load of approximately 9.0-10.5 kN at the design deflection; (2) a Ss 25 or Ss 36 screw spike with a coarse thread (M22 × 1.5 for the Ss 25, M24 × 2.0 for the Ss 36) that is embedded into the concrete sleeper with a two-component epoxy mortar capsule or a mechanical plastic dowel; (3) a Wpf 14 or similar angle guide plate that positions the clamp and distributes lateral load; and (4) an Ng 4 or Ng 6 nylon insulator providing electrical isolation for track-circuit signalling. The complete assembly is installed using a calibrated Vossloh WSM-type installation machine that applies a defined torque of 250-350 Nm to the screw spike while measuring the resulting clip deflection.\n\n"
    "The Vossloh W series (W 14, W 21, W 30) and DFF (DFF 21, DFF 30) are alternative geometries for slab-track applications such as the Rheda 2000, Rheda-Sydney, or ATD systems used on tunnels, bridges, and high-speed viaducts. The W 30 is specified on the Madrid-Barcelona-French-border high-speed line, the Bologna-Florence corridor, and the Beijing-Tianjin and Wuhan-Guangzhou high-speed lines in China, all of which operate at 300-350 km/h. The DFF (Doppel-Feder-Feder) double-spring clamp is reserved for applications requiring toe loads above 14 kN per clamp, such as heavy-haul iron-ore lines in Western Australia and South Africa where axle loads reach 40 tonnes on the Richards Bay iron-ore line.\n\n"
    "Material specifications for Vossloh clamps follow EN 10089 grade 38Si7 or 51CrV4 with controlled inclusion content, and the wire rod is supplied exclusively by European mills (Voestalpine, Saarstahl) to meet fatigue and cleanliness requirements. Surface protection is a 12-18 μm phosphate coating (Bonderite or Delta-MKS) topped with a wax-based dry-film lubricant (Molykote D-321R or equivalent) that reduces installation friction and improves thread engagement. The screw spikes are produced from 41Cr4 or 42CrMo4 quenched and tempered alloy steel, with Grade 10.9 mechanical properties (tensile 1,040 MPa minimum, yield 940 MPa minimum) and a 25-35 μm Dacromet or Geomet coating for corrosion protection.\n\n"
    "For TradeGo customers serving North African tenders (Algeria, Morocco, Egypt, Tunisia), Middle Eastern high-speed projects (Saudi Arabia's Haramain, UAE Etihad Rail, Qatar's Doha Metro), and Latin American metro systems, Vossloh-equivalent clamps manufactured in China and Türkiye are widely accepted. The key procurement specifications are: (1) third-party tested toe load within ±10% of 9.0 kN at 13 mm deflection for Skl 14, (2) fatigue life exceeding 3 million cycles at ±1.2 mm deflection amplitude per EN 13146-4, (3) electrical resistance exceeding 10 kΩ per EN 13146-8 with new nylon insulator, (4) coating thickness 12-18 μm phosphate + 8-12 μm wax, and (5) full material traceability with 3.1 certificates per EN 10204."
)

s3_zh = (
    "Vossloh 扣件系统在德国 Werdohl 设计，目前归入 Vossloh AG 轨道交通基础设施部门，确立了高速铁路扣件性能的全球基准。Vossloh 产品层次始于 Skl 弹条（Spannklemme），自 1970 年代以来一直主导欧洲重载和高速应用。Skl 14 是最高速度 250 km/h 的有砟轨道的主力，Skl 21 覆盖 32.5 吨轴重的重载货运，Skl 24/Skl 30 系列保留用于 250 km/h 以上的高速走廊。\n\n"
    "Vossloh Skl 14 系统包括四个主要部件：(1) Skl 14 弹条本身，由 3 mm 厚热轧弹簧钢冲压而成，线径 14 mm，设计挠度下单扣件扣压力约 9.0-10.5 kN；(2) Ss 25 或 Ss 36 螺纹道钉，粗糙螺纹（M22×1.5 用于 Ss 25，M24×2.0 用于 Ss 36），用双组份环氧砂浆胶囊或机械塑料套筒嵌入混凝土轨枕；(3) Wpf 14 或类似的角形导向板，定位弹条并分配横向载荷；(4) Ng 4 或 Ng 6 尼龙绝缘体，为轨道电路信号提供电气隔离。\n\n"
    "Vossloh W 系列（W 14、W 21、W 30）和 DFF（DFF 21、DFF 30）是无砟轨道应用的替代几何结构，例如 Rheda 2000、Rheda-Sydney 或 ATD 系统，用于隧道、桥梁和高速高架桥。W 30 在马德里-巴塞罗那-法国边境高速线、博洛尼亚-佛罗伦萨走廊以及中国的北京-天津和武汉-广州高速线（均为 300-350 km/h 运行）上指定使用。DFF（双弹条）双弹簧夹保留用于需要单夹具 14 kN 以上扣压力的应用。\n\n"
    "对于服务于北非招标（阿尔及利亚、摩洛哥、埃及、突尼斯）、中东高速项目（沙特阿拉伯的哈拉曼、阿拉伯联合酋长国的伊蒂哈德铁路、卡塔尔多哈地铁）和拉丁美洲地铁系统的 TradeGo 客户，在中国和土耳其制造的 Vossloh 等效弹条被广泛接受。关键的采购规格包括：(1) 第三方测试的 Skl 14 在 13 mm 挠度时扣压力在 9.0 kN 的 ±10% 范围内；(2) 按 EN 13146-4 在 ±1.2 mm 挠度幅值下疲劳寿命超过 300 万次；(3) 按 EN 13146-8 使用新尼龙绝缘体时电阻超过 10 kΩ。\n\n"
    "Vossloh 弹条的材料规格遵循 EN 10089 38Si7 或 51CrV4 等级，并具有受控的夹杂物含量。线材由欧洲工厂（Voestalpine、Saarstahl）独家供应，以满足疲劳和清洁度要求。表面保护是 12-18 μm 磷酸盐涂层（Bonderite 或 Delta-MKS），顶部涂有蜡基干膜润滑剂（Molykote D-321R 或等效产品），可减少安装摩擦并改善螺纹啮合。螺钉道钉由 41Cr4 或 42CrMo4 淬火回火合金钢制成，具有 10.9 级的机械性能（最小抗拉强度 1,040 MPa，最小屈服强度 940 MPa）和 25-35 μm 的 Dacromet 或 Geomet 防腐涂层。"
)

s3_es = (
    "Los sistemas de sujeción Vossloh, diseñados en Werdohl, Alemania, y ahora consolidados bajo la división de infraestructura ferroviaria de Vossloh AG, establecen el estándar global de rendimiento de sujeción para rieles de alta velocidad. La jerarquía de productos Vossloh comienza con la grapa de tensión Skl (Spannklemme), que ha dominado las aplicaciones europeas de carga pesada y alta velocidad desde la década de 1970. Skl 14 es la opción principal para vía con balasto a velocidades de hasta 250 km/h, Skl 21 cubre carga pesada hasta 32,5 toneladas por eje, y la serie Skl 24/Skl 30 está reservada para corredores de alta velocidad por encima de 250 km/h.\n\n"
    "Un sistema Vossloh Skl 14 comprende cuatro componentes principales: (1) la grapa de tensión Skl 14, un estampado de acero para resortes laminado en caliente de 3 mm de espesor con sección transversal de alambre de 14 mm de diámetro y carga de punta de aproximadamente 9.0-10.5 kN a la deflexión de diseño; (2) un tirafondo Ss 25 o Ss 36 con rosca gruesa; (3) una placa guía angular Wpf 14 que posiciona la grapa y distribuye la carga lateral; y (4) un aislante de nailon Ng 4 o Ng 6 que proporciona aislamiento eléctrico para la señalización del circuito de vía.\n\n"
    "Las series Vossloh W (W 14, W 21, W 30) y DFF (DFF 21, DFF 30) son geometrías alternativas para aplicaciones de vía en losa como los sistemas Rheda 2000, Rheda-Sydney o ATD utilizados en túneles, puentes y viaductos de alta velocidad. El W 30 se especifica en la línea de alta velocidad Madrid-Barcelona-frontera francesa.\n\n"
    "Para los clientes de TradeGo que sirven licitaciones del norte de África (Argelia, Marruecos, Egipto, Túnez), proyectos de alta velocidad de Oriente Medio (Haramain de Arabia Saudita, Etihad Rail de EAU, Metro de Doha de Qatar) y sistemas de metro latinoamericanos, las grapas equivalentes a Vossloh fabricadas en China y Turquía son ampliamente aceptadas. Las especificaciones clave de adquisición son: (1) carga de punta probada por terceros dentro del ±10% de 9,0 kN a 13 mm de deflexión para Skl 14, (2) vida de fatiga superior a 3 millones de ciclos a amplitud de deflexión de ±1,2 mm según EN 13146-4, (3) resistencia eléctrica superior a 10 kΩ según EN 13146-8 con aislante de nailon nuevo."
)

s3_ar = (
    "تضع أنظمة تثبيت Vossloh، المصممة في Werdohl بألمانيا، والمدمجة الآن تحت قسم البنية التحتية للسكك الحديدية في Vossloh AG، المعيار العالمي لأداء تثبيت السكك الحديدية عالية السرعة. تبدأ تسلسل منتجات Vossloh بمشبك التوتر Skl (Spannklemme)، الذي هيمن على التطبيقات الأوروبية للخدمة الشاقة وعالية السرعة منذ السبعينيات.\n\n"
    "يتكون نظام Vossloh Skl 14 من أربعة مكونات رئيسية: (1) مشبك التوتر Skl 14 نفسه، وهو ختم من الفولاذ الزنبركي المدرفلة على الساخن بسمك 3 mm مع مقطع عرضي للسلك بقطر 14 mm وحمل نقطة يبلغ حوالي 9.0-10.5 kN عند الانحراف التصميمي؛ (2) مسمار لولبي Ss 25 أو Ss 36 بخيط خشن؛ (3) لوحة توجيه زاوية Wpf 14 تضع المشبك وتوزع الحمل الجانبي؛ و (4) عازل نايلون Ng 4 أو Ng 6 يوفر العزل الكهربائي لإشارات دائرة السكة.\n\n"
    "بالنسبة لعملاء TradeGo الذين يخدمون المناقصات في شمال أفريقيا (الجزائر والمغرب ومصر وتونس) ومشاريع الشرق الأوسط عالية السرعة (الحرمين في المملكة العربية السعودية، وسكك حديد الاتحاد في الإمارات العربية المتحدة، ومترو الدوحة في قطر) وأنظمة المترو في أمريكا اللاتينية، يتم قبول مشابك Vossloh المكافئة المصنعة في الصين وتركيا على نطاق واسع."
)

s3_fr = (
    "Les systèmes de fixation Vossloh, conçus à Werdohl, en Allemagne, et maintenant consolidés sous la division d'infrastructure ferroviaire de Vossloh AG, établissent la référence mondiale en matière de performance de fixation ferroviaire à grande vitesse. La hiérarchie des produits Vossloh commence par la grappe de tension Skl (Spannklemme), qui domine les applications européennes à fort tonnage et à grande vitesse depuis les années 1970.\n\n"
    "Un système Vossloh Skl 14 comprend quatre composants principaux : (1) la grappe de tension Skl 14 elle-même, un emboutissage en acier à ressorts laminé à chaud de 3 mm d'épaisseur avec une section transversale de fil de 14 mm de diamètre et une charge de pointe d'environ 9,0-10,5 kN à la déflexion de conception ; (2) un tirefond Ss 25 ou Ss 36 avec un filetage grossier ; (3) une plaque de guidage angulaire Wpf 14 qui positionne la grappe et distribue la charge latérale ; et (4) un isolant en nylon Ng 4 ou Ng 6 fournissant l'isolation électrique pour la signalisation du circuit de voie.\n\n"
    "Pour les clients TradeGo desservant les appels d'offres d'Afrique du Nord (Algérie, Maroc, Égypte, Tunisie), les projets à grande vitesse du Moyen-Orient (Haramain d'Arabie saoudite, Etihad Rail des EAU, métro de Doha au Qatar) et les systèmes de métro latino-américains, les grappes équivalentes Vossloh fabriquées en Chine et en Turquie sont largement acceptées."
)

s3_pt = (
    "Os sistemas de fixação Vossloh, projetados em Werdohl, Alemanha, e agora consolidados sob a divisão de infraestrutura ferroviária da Vossloh AG, estabelecem o padrão global de desempenho de fixação ferroviária de alta velocidade. A hierarquia de produtos Vossloh começa com a braçadeira de tensão Skl (Spannklemme), que domina as aplicações europeias de carga pesada e alta velocidade desde a década de 1970.\n\n"
    "Um sistema Vossloh Skl 14 compreende quatro componentes principais: (1) a braçadeira de tensão Skl 14 em si, uma estampagem de aço para molas laminado a quente com 3 mm de espessura com seção transversal de fio de 14 mm de diâmetro e carga de ponta de aproximadamente 9,0-10,5 kN na deflexão de projeto; (2) um parafuso Ss 25 ou Ss 36 com rosca grossa; (3) uma placa guia angular Wpf 14 que posiciona a braçadeira e distribui a carga lateral; e (4) um isolante de nylon Ng 4 ou Ng 6 fornecendo isolamento elétrico para sinalização de circuito de via.\n\n"
    "Para clientes da TradeGo que atendem licitações no norte da África (Argélia, Marrocos, Egito, Tunísia), projetos de alta velocidade no Oriente Médio (Haramain da Arábia Saudita, Etihad Rail dos EAU, metrô de Doha do Catar) e sistemas de metrô latino-americanos, as braçadeiras equivalentes Vossloh fabricadas na China e Turquia são amplamente aceitas."
)

s3_ru = (
    "Системы крепления Vossloh, разработанные в Вердоле, Германия, и теперь объединенные подразделением железнодорожной инфраструктуры Vossloh AG, устанавливают мировой стандарт производительности крепления высокоскоростных железных дорог. Иерархия продуктов Vossloh начинается с натяжного зажима Skl (Spannklemme), который доминирует в европейских тяжеловесных и высокоскоростных применениях с 1970-х годов.\n\n"
    "Система Vossloh Skl 14 состоит из четырех основных компонентов: (1) сам натяжной зажим Skl 14, штамповка из горячекатаной пружинной стали толщиной 3 мм с поперечным сечением проволоки диаметром 14 мм и нагрузкой на носке приблизительно 9,0-10,5 кН при проектном прогибе; (2) шуруп-костыль Ss 25 или Ss 36 с крупной резьбой; (3) угловая направляющая пластина Wpf 14, которая позиционирует зажим и распределяет боковую нагрузку; и (4) нейлоновый изолятор Ng 4 или Ng 6, обеспечивающий электрическую изоляцию для сигнализации рельсовой цепи.\n\n"
    "Для клиентов TradeGo, обслуживающих североафриканские тендеры (Алжир, Марокко, Египет, Тунис), ближневосточные высокоскоростные проекты (Haramain в Саудовской Аравии, Etihad Rail в ОАЭ, метро Доха в Катаре) и латиноамериканские системы метро, широко принимаются эквивалентные зажимы Vossloh, изготовленные в Китае и Турции."
)

s3_ja = (
    "ドイツの Werdohl で設計され、現在 Vossloh AG の鉄道インフラ部門の下に統合された Vossloh 締結システムは、高速鉄道締結性能の世界的なベンチマークを設定しています。Vossloh 製品階層は、1970 年代からヨーロッパの重荷重および高速用途を支配してきた Skl テンションクランプ (Spannklemme) から始まります。\n\n"
    "Vossloh Skl 14 システムは 4 つの主要コンポーネントで構成されています：(1) Skl 14 テンションクランプ自体、厚さ 3 mm の熱間圧延ばね鋼のスタンピング、線径 14 mm、設計撓み時の爪先荷重約 9.0-10.5 kN；(2) 粗いねじを持つ Ss 25 または Ss 36 ねじスパイク；(3) クランプを位置決めし横方向の荷重を分散する Wpf 14 角度ガイドプレート；(4) 軌道回路信号用の電気的絶縁を提供する Ng 4 または Ng 6 ナイロンインシュレーター。\n\n"
    "北アフリカの入札（アルジェリア、モロッコ、エジプト、チュニジア）、中東の高速プロジェクト（サウジアラビアの Haramain、UAE の Etihad Rail、カタールのドハメトロ）、ラテンアメリカのメトロシステムに対応する TradeGo のお客様向けに、中国とトルコで製造された Vossloh 相当クランプが広く受け入れられています。"
)

s3_de = (
    "Vossloh-Befestigungssysteme, entwickelt in Werdohl, Deutschland, und nun unter der Bahninfrastruktur-Sparte der Vossloh AG konsolidiert, setzen den globalen Maßstab für die Leistung von Hochgeschwindigkeits-Schienenbefestigungen. Die Vossloh-Produkthierarchie beginnt mit der Skl-Spannklemme, die seit den 1970er Jahren europäische Schwerlast- und Hochgeschwindigkeitsanwendungen dominiert.\n\n"
    "Ein Vossloh Skl 14-System umfasst vier Hauptkomponenten: (1) die Skl 14-Spannklemme selbst, ein 3 mm dickes warmgewalztes Federstahl-Stanzteil mit 14 mm Drahtdurchmesser und einer Spitzenlast von ca. 9,0-10,5 kN bei der konstruktiven Durchbiegung; (2) eine Ss 25 oder Ss 36 Schraubenspitze mit grobem Gewinde; (3) eine Wpf 14 Winkelführungsplatte, die die Klemme positioniert und die Querlast verteilt; und (4) ein Ng 4 oder Ng 6 Nylon-Isolator, der die elektrische Isolierung für die Gleisstromkreis-Signalisierung bereitstellt.\n\n"
    "Für TradeGo-Kunden, die nordafrikanische Ausschreibungen (Algerien, Marokko, Ägypten, Tunesien), nahöstliche Hochgeschwindigkeitsprojekte (Haramain in Saudi-Arabien, Etihad Rail in den VAE, Doha Metro in Katar) und lateinamerikanische U-Bahn-Systeme bedienen, sind in China und der Türkei hergestellte Vossloh-Äquivalentklemmen weit verbreitet."
)

s3_hi = (
    "जर्मनी के Werdohl में डिज़ाइन किए गए और अब Vossloh AG के रेल इंफ्रास्ट्रक्चर डिवीजन के तहत समेकित Vossloh फास्टनिंग सिस्टम, हाई-स्पीड रेल फास्टनिंग प्रदर्शन के लिए वैश्विक मानक स्थापित करते हैं। Vossloh उत्पाद पदानुक्रम 1970 के दशक से यूरोपीय भारी-भार और हाई-स्पीड अनुप्रयोगों पर हावी Skl टेंशन क्लैम्प (Spannklemme) से शुरू होता है।\n\n"
    "Vossloh Skl 14 सिस्टम में चार प्राथमिक घटक शामिल हैं: (1) Skl 14 टेंशन क्लैम्प स्वयं, 3 mm मोटी गर्म-लुढ़काई स्प्रिंग स्टील की स्टैम्पिंग, 14 mm व्यास के तार क्रॉस-सेक्शन और डिज़ाइन विक्षेपण पर लगभग 9.0-10.5 kN की पैर की उंगली भार के साथ; (2) मोटे धागे वाला Ss 25 या Ss 36 स्क्रू स्पाइक; (3) Wpf 14 एंगल गाइड प्लेट जो क्लैम्प को स्थान देती है और पार्श्व भार वितरित करती है; और (4) ट्रैक-सर्किट सिग्नलिंग के लिए विद्युत इन्सुलेशन प्रदान करने वाला Ng 4 या Ng 6 नायलॉन इन्सुलेटर।\n\n"
    "उत्तरी अफ्रीकी निविदाओं (अल्जीरिया, मोरक्को, मिस्र, ट्यूनीशिया), मध्य पूर्व हाई-स्पीड परियोजनाओं (सऊदी अरब का हरमेन, UAE का एतिहाद रेल, कतर का दोहा मेट्रो) और लैटिन अमेरिकी मेट्रो सिस्टम की सेवा करने वाले TradeGo ग्राहकों के लिए, चीन और तुर्की में निर्मित Vossloh समकक्ष क्लैम्प व्यापक रूप से स्वीकृत हैं।"
)

s3_body = t(s3_en, s3_zh, s3_es, s3_ar, s3_fr, s3_pt, s3_ru, s3_ja, s3_de, s3_hi)

print("Sections 1-3 built, building 4...")

# Save what we have so far
output = {
    's1_heading': s1_heading,
    's1_body': s1_body,
    's2_heading': s2_heading,
    's2_body': s2_body,
    's3_heading': s3_heading,
    's3_body': s3_body,
}
with open('/tmp/railway_partial.json', 'w') as f:
    json.dump(output, f)
print("Saved partial")
